export const TODAY_SELECT = 'TODAY_SELECT'
export const TODAY_REQUEST = 'TODAY_REQUEST'
export const TODAY_RECEIVE = 'TODAY_RECEIVE'
export const TODAY_INVALIDATE = 'TODAY_INVALIDATE'

export const INVALIDATE_ITEM = 'INVALIDATE_ITEM'
export const REQUEST_ITEM = 'REQUEST_ITEM'
export const RECEIVE_ITEM = 'RECEIVE_ITEM'
export const SELECT_ITEM = 'SELECT_ITEM'
