export const OPTIONS_TODAY = 'OPTIONS_TODAY'
export const REQUEST_TODAY = 'REQUEST_TODAY'
export const RECEIVE_TODAY = 'RECEIVE_TODAY'
export const INVALIDATE_TODAY = 'INVALIDATE_TODAY'

export const INVALIDATE_ITEM = 'INVALIDATE_ITEM'
export const REQUEST_ITEM = 'REQUEST_ITEM'
export const RECEIVE_ITEM = 'RECEIVE_ITEM'
export const SELECT_ITEM = 'SELECT_ITEM'
